### ISSUE TITLE
6.1LTS Kernel version parse failed

### ISSUE THREAD

**Issue by right-0903** [intel-gpu/intel-gpu-i915-backports#131]
We support and test Ubuntu 22.04 hwe kernel which has been moved to 6.2 , and we are working to add support for that.
6.1 LTS will be compliable but since Testing is not being done so we cannot commit to support 6.1 lts version.

_Originally posted by @ayazahma in https://github.com/intel-gpu/intel-gpu-i915-backports/issues/99#issuecomment-1672636106_

**Comment by right-0903** [comment]
even if I can replace kerver manually, but there are errors when build 

```c
/home/user/i915/backport-include/drm/intel-gtt.h:14:36: error：implicit declaration of function ‘intel_gtt_insert_page’; did you mean ‘intel_gmch_gtt_insert_page’? [-Werror=implicit-function-declaration]
   14 | #define intel_gmch_gtt_insert_page intel_gtt_insert_page

```

I also notice there are several backport macros for linux6+, but there are many things to change, afaik, vma use maple tree instead of rbtree since linux 6, but SVM still use the methods for rbtree. I doubt if it is compliable for linux 6+

**Comment by right-0903** [comment]
now It works with 6.1LTS. I have committed changes in my forked repo.
