### ISSUE TITLE
dkms compilation failed on ubuntu 24.04

### ISSUE THREAD

**Issue by ye-luo** [intel-gpu/intel-gpu-i915-backports#207]
I failed to install intel-i915-dkms on ubuntu 24.04
I followed https://dgpu-docs.intel.com/driver/client/overview.html to set up the apt repo
```
$ sudo apt install intel-i915-dkms
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  intel-i915-dkms
0 upgraded, 1 newly installed, 0 to remove and 24 not upgraded.
Need to get 0 B/3,028 kB of archives.
After this operation, 19.3 MB of additional disk space will be used.
Selecting previously unselected package intel-i915-dkms.
(Reading database ... 284010 files and directories currently installed.)
Preparing to unpack .../intel-i915-dkms_1.24.6.12.240823.13+i14-1_all.deb ...
Unpacking intel-i915-dkms (1.24.6.12.240823.13+i14-1) ...
Setting up intel-i915-dkms (1.24.6.12.240823.13+i14-1) ...
Loading new intel-i915-dkms-1.24.6.12.240823.13 DKMS files...
AUXILIARY_BUS is enabled for 6.8.0-51-generic.
Building for 6.8.0-51-generic
Building initial module for 6.8.0-51-generic
AUXILIARY_BUS is enabled for 6.8.0-51-generic.
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/intel-i915-dkms.0.crash'
Error! Bad return status for module build on kernel: 6.8.0-51-generic (x86_64)
Consult /var/lib/dkms/intel-i915-dkms/1.24.6.12.240823.13/build/make.log for more information.
dpkg: error processing package intel-i915-dkms (--configure):
 installed intel-i915-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 intel-i915-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

My OS is ubuntu 24.04.1 with `6.8.0-51-generic` kernel.

[make.log](https://github.com/user-attachments/files/18215452/make.log)

Found a very similar post https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/2024-5-GPU-install-fails-intel-i915-dkms-syntax-error/m-p/1649859

**Comment by ye-luo** [comment]
The same error occur when I made `intel-i915-dkms_1.24.6.12.240823.13.6.8.0.48+i1-1_all.deb` based on this repo.

**Comment by smuqthya** [comment]
@ye-luo  This error is due to latest kernel version. Please go through the version doc for the last verified version. 
https://github.com/intel-gpu/intel-gpu-i915-backports/blob/backport/main/versions

**Comment by knayana-gse** [comment]
Issue is fixed in latest release. tag: https://github.com/intel-gpu/intel-gpu-i915-backports/releases/tag/I915_24WW52.1_1057.13_24.7.9_241015.10 
https://github.com/intel-gpu/intel-gpu-i915-backports/blob/backport/main/versions#L4
